### ISSUE TITLE
tutorial for linux user

### ISSUE THREAD

**Issue by bingining** [sunyuting83/v2rss-go#5]
Can someone give some instructions on how to use it after intallation on linux system?

**Comment by sunyuting83** [comment]
if you installed it on your VPS. You need add the vhost config to your nginx or other web service.
if you installed it on your computer.just need add "http://localhost:5500" on your subscribe of v2ray client.
can you speack Chinese?

**Comment by zuchengchen** [comment]
谢谢！我已经搞懂怎么使用了

**Comment by sunyuting83** [comment]
最近tg频道不更新了。可以看README里推荐的项目。
